#!/usr/bin/env bash
# setup-workspace.sh — one-time (and idempotent re-runnable) workspace setup.
#
#   1. Clone every repository in config/repos.json into repositories/<name>
#      and enable extensions.worktreeConfig on each (needed so sparse-checkout
#      works per-worktree inside sandboxed sessions).
#   2. Generate .claude/settings.json (root sandbox) and
#      repositories/.claude/settings.json from templates/root/.
#   3. Install the pre-push hook for every repo/worktree under this workspace
#      via core.hooksPath in a generated .gitconfig-workspace, wired into
#      ~/.gitconfig with an includeIf scoped to this directory.
#   4. Install the cmux helper scripts to ~/.cmux-wait.sh / ~/.cmux-state.sh
#      (required by wait-for-worker; called via literal ~/ paths from
#      sandbox-excluded commands).
#
# Usage: scripts/setup-workspace.sh [--skip-clone] [--dry-run]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

WORKSPACE_ROOT="$(workspace_root)"
export WORKSPACE_ROOT

SKIP_CLONE=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --skip-clone) SKIP_CLONE=true ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) die "unknown argument: $arg" ;;
  esac
done

run() {
  if $DRY_RUN; then log "[dry-run] $*"; else "$@"; fi
}

require_cmd git
require_cmd jq
command -v gh >/dev/null 2>&1 || warn "gh (GitHub CLI) not found — PR creation will not work until installed."
command -v cmux >/dev/null 2>&1 || warn "cmux not found — /open-task will fall back to clipboard mode (no 3-tab orchestration)."

REPOS_JSON="$WORKSPACE_ROOT/config/repos.json"
[ -f "$REPOS_JSON" ] || die "config/repos.json not found"
jq -e '.repositories | type == "array"' "$REPOS_JSON" >/dev/null \
  || die "config/repos.json: .repositories must be an array"

# ---------------------------------------------------------------- 1. clones
if ! $SKIP_CLONE; then
  info "Cloning target repositories into repositories/"
  count="$(jq '.repositories | length' "$REPOS_JSON")"
  i=0
  while [ "$i" -lt "$count" ]; do
    name="$(jq -r ".repositories[$i].name" "$REPOS_JSON")"
    url="$(jq -r ".repositories[$i].url" "$REPOS_JSON")"
    i=$((i + 1))
    [ -n "$name" ] && [ "$name" != "null" ] || die "repos.json entry $((i-1)): missing name"
    [ -n "$url" ] && [ "$url" != "null" ] || die "repos.json entry '$name': missing url"
    dest="$WORKSPACE_ROOT/repositories/$name"
    if [ -d "$dest/.git" ]; then
      log "  - $name: already cloned, skipping"
    else
      case "$url" in
        *your-org*) warn "  - $name: url still points at the placeholder org ($url) — edit config/repos.json. Skipping."; continue ;;
      esac
      info "  - cloning $name ($url)"
      run git clone "$url" "$dest"
    fi
    # Required for per-worktree sparse-checkout of knowledge repos, and safe
    # for all repos.
    run git -C "$dest" config extensions.worktreeConfig true
  done
fi

# ------------------------------------------------------------- 2. settings
info "Generating layer settings from templates/root/"
run mkdir -p "$WORKSPACE_ROOT/.claude" "$WORKSPACE_ROOT/repositories/.claude"
if ! $DRY_RUN; then
  render_template "$WORKSPACE_ROOT/templates/root/claude-settings.json" \
    > "$WORKSPACE_ROOT/.claude/settings.json"
  render_template "$WORKSPACE_ROOT/templates/root/repositories-settings.json" \
    > "$WORKSPACE_ROOT/repositories/.claude/settings.json"
fi

# ------------------------------------------------------------- 3. git hooks
info "Installing pre-push hook (core.hooksPath via ~/.gitconfig includeIf)"
run chmod +x "$WORKSPACE_ROOT/.githooks/pre-push"
if ! $DRY_RUN; then
  cat > "$WORKSPACE_ROOT/.gitconfig-workspace" <<EOF
# Generated by setup-workspace.sh — applied to every git repo under this
# workspace through the includeIf entry in ~/.gitconfig. Do not commit.
[core]
	hooksPath = $WORKSPACE_ROOT/.githooks
EOF
fi
INCLUDE_KEY="includeIf.gitdir:$WORKSPACE_ROOT/.path"
CURRENT_INCLUDE="$(git config --global --get "$INCLUDE_KEY" 2>/dev/null || true)"
if [ "$CURRENT_INCLUDE" != "$WORKSPACE_ROOT/.gitconfig-workspace" ]; then
  run git config --global "$INCLUDE_KEY" "$WORKSPACE_ROOT/.gitconfig-workspace"
fi

ALLOWED_ORGS="$(json_get "$WORKSPACE_ROOT/config/workspace.json" '.allowed_push_orgs | join(", ")')"
if [ -z "$ALLOWED_ORGS" ]; then
  warn "allowed_push_orgs is empty in config/workspace.json — pushes are unrestricted (the hook only warns). NOTE: the hook applies to this workspace repo itself too; add your own org before restricting."
else
  log "  push destinations restricted to: $ALLOWED_ORGS"
fi

# ----------------------------------------------------------- 4. cmux helpers
info "Installing cmux helper scripts to ~/"
for helper in cmux-wait.sh cmux-state.sh; do
  src="$WORKSPACE_ROOT/scripts/cmux/$helper"
  dst="$HOME/.$helper"
  if [ ! -f "$src" ]; then
    warn "  - $helper missing from scripts/cmux/ (skipping)"
    continue
  fi
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    log "  - ~/.$helper up to date"
  else
    run cp "$src" "$dst"
    run chmod +x "$dst"
    log "  - installed ~/.$helper"
  fi
done

info "Setup complete."
log ""
log "Next steps:"
log "  1. Restart claude in $WORKSPACE_ROOT so the generated root settings apply"
log "     (accept the workspace trust dialog — without trust, permissions.allow is ignored)."
log "  2. Run /open-task to start work on a ticket."
