#!/usr/bin/env bash
# setup-workspace.sh — one-time (and idempotent re-runnable) workspace setup.
#
#   1. Clone every repository in config/repos.json into repositories/<name>
#      and enable extensions.worktreeConfig on each (needed so sparse-checkout
#      works per-worktree inside sandboxed sessions).
#   2. Generate .claude/settings.json (root sandbox) and
#      repositories/.claude/settings.json from templates/root/.
#   3. Install the pre-push hook for every repo/worktree under this workspace
#      via core.hooksPath in a generated .gitconfig-workspace, wired into
#      ~/.gitconfig with an includeIf scoped to this directory.
#   4. Install the cmux helper scripts to ~/.cmux-wait.sh / ~/.cmux-state.sh
#      (required by wait-for-worker; called via literal ~/ paths from
#      sandbox-excluded commands).
#
# Usage: scripts/setup-workspace.sh [--skip-clone] [--dry-run]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

WORKSPACE_ROOT="$(canonicalize_path "$(workspace_root)")"
export WORKSPACE_ROOT
STATE_ROOT="$(state_root)"
export STATE_ROOT
CONFIG_DIR="$(config_dir)"
export CONFIG_DIR

SKIP_CLONE=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --skip-clone) SKIP_CLONE=true ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) die "unknown argument: $arg" ;;
  esac
done

run() {
  if $DRY_RUN; then log "[dry-run] $*"; else "$@"; fi
}

require_cmd git
require_cmd jq
command -v gh >/dev/null 2>&1 || warn "gh (GitHub CLI) not found — PR creation will not work until installed."
command -v cmux >/dev/null 2>&1 || warn "cmux not found — /open-task will fall back to clipboard mode (no 3-tab orchestration)."

REPOS_JSON="$CONFIG_DIR/repos.json"
[ -f "$REPOS_JSON" ] || die "$REPOS_JSON not found"
jq -e '.repositories | type == "array"' "$REPOS_JSON" >/dev/null \
  || die "$REPOS_JSON: .repositories must be an array"

# ---------------------------------------------------------------- 1. clones
if ! $SKIP_CLONE; then
  info "Cloning target repositories into repositories/"
  count="$(jq '.repositories | length' "$REPOS_JSON")"
  i=0
  while [ "$i" -lt "$count" ]; do
    name="$(jq -r ".repositories[$i].name" "$REPOS_JSON")"
    url="$(jq -r ".repositories[$i].url" "$REPOS_JSON")"
    i=$((i + 1))
    [ -n "$name" ] && [ "$name" != "null" ] || die "repos.json entry $((i-1)): missing name"
    [ -n "$url" ] && [ "$url" != "null" ] || die "repos.json entry '$name': missing url"
    dest="$STATE_ROOT/repositories/$name"
    if [ -d "$dest/.git" ]; then
      log "  - $name: already cloned, skipping"
    else
      case "$url" in
        *your-org*) warn "  - $name: url still points at the placeholder org ($url) — edit $REPOS_JSON. Skipping."; continue ;;
      esac
      info "  - cloning $name ($url)"
      run git clone "$url" "$dest"
    fi
    # Required for per-worktree sparse-checkout of knowledge repos, and safe
    # for all repos.
    run git -C "$dest" config extensions.worktreeConfig true
  done
fi

# ------------------------------------------------------------- 2. settings
info "Generating layer settings from templates/root/"
run mkdir -p "$WORKSPACE_ROOT/.claude" "$STATE_ROOT/repositories/.claude"
if ! $DRY_RUN; then
  render_template "$WORKSPACE_ROOT/templates/root/claude-settings.json" \
    > "$WORKSPACE_ROOT/.claude/settings.json"
  render_template "$WORKSPACE_ROOT/templates/root/repositories-settings.json" \
    > "$STATE_ROOT/repositories/.claude/settings.json"
fi

# ------------------------------------------------------------- 3. git hooks
info "Installing pre-push hook (core.hooksPath via ~/.gitconfig includeIf)"
run chmod +x "$WORKSPACE_ROOT/.githooks/pre-push"
if ! $DRY_RUN; then
  cat > "$WORKSPACE_ROOT/.gitconfig-workspace" <<EOF
# Generated by setup-workspace.sh for the shared tool checkout. Do not commit.
# Keep per-workspace values out of this shared file: writing them here creates
# last-setup-wins cross-workspace contamination. Workspace scopes use their own
# config_dir/gitconfig-workspace include files below.
[core]
	hooksPath = $WORKSPACE_ROOT/.githooks
[mrw]
	configDir = $(canonicalize_path "$WORKSPACE_ROOT/config")
EOF
  if [ "$(config_mode)" = "workspace" ]; then
    cat > "$CONFIG_DIR/gitconfig-workspace" <<EOF
# Generated by setup-workspace.sh for this workspace scope. Do not commit.
[core]
	hooksPath = $WORKSPACE_ROOT/.githooks
[mrw]
	configDir = $CONFIG_DIR
EOF
  fi
fi
# Scope the hook to BOTH the tool checkout (which is itself a git repo — the
# management console) AND the state_root where the managed origins/worktrees
# live. When they are equal (default, unset state_root) the second iteration is
# a redundant no-op. Covering tool_home too keeps the org/host guard on pushes
# of the console repo itself — a fresh clone with an externalized state_root
# would otherwise leave the console repo's pushes unguarded.
_tool_include="$WORKSPACE_ROOT/.gitconfig-workspace"
_state_include="$_tool_include"
if [ "$(config_mode)" = "workspace" ]; then
  _state_include="$CONFIG_DIR/gitconfig-workspace"
fi
for _scope_target in "$WORKSPACE_ROOT|$_tool_include" "$STATE_ROOT|$_state_include"; do
  _scope="${_scope_target%%|*}"
  _target="${_scope_target#*|}"
  INCLUDE_KEY="includeIf.gitdir:$_scope/.path"
  CURRENT_INCLUDE="$(git config --global --get "$INCLUDE_KEY" 2>/dev/null || true)"
  if [ "$CURRENT_INCLUDE" != "$_target" ]; then
    run git config --global "$INCLUDE_KEY" "$_target"
  fi
done

ALLOWED_ORGS="$(json_get "$CONFIG_DIR/workspace.json" '.allowed_push_orgs | join(", ")')"
if [ -z "$ALLOWED_ORGS" ]; then
  warn "allowed_push_orgs is empty in $CONFIG_DIR/workspace.json — pushes are unrestricted (the hook only warns). NOTE: the hook applies to this workspace repo itself too; add your own org before restricting."
else
  log "  push destinations restricted to: $ALLOWED_ORGS"
fi

# ----------------------------------------------------------- 4. cmux helpers
info "Installing cmux helper scripts to ~/"
for helper in cmux-wait.sh cmux-state.sh; do
  src="$WORKSPACE_ROOT/scripts/cmux/$helper"
  dst="$HOME/.$helper"
  if [ ! -f "$src" ]; then
    warn "  - $helper missing from scripts/cmux/ (skipping)"
    continue
  fi
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    log "  - ~/.$helper up to date"
  else
    run cp "$src" "$dst"
    run chmod +x "$dst"
    log "  - installed ~/.$helper"
  fi
done

info "Setup complete."
log ""
log "Next steps:"
log "  1. Restart claude in $WORKSPACE_ROOT so the generated root settings apply"
log "     (accept the workspace trust dialog — without trust, permissions.allow is ignored)."
log "  2. Run /open-task to start work on a ticket."
